image: maven:3.9-eclipse-temurin-21

stages:
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  script:
    - mvn clean test || TEST_EXIT_CODE=$?
    - mvn allure:report
    - exit ${TEST_EXIT_CODE:-0}
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - target/site/allure-maven-plugin/
      - target/allure-results/
